# Generated by Django 4.0.3 on 2024-01-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilite',
            name='idMed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.specialite'),
        ),
        migrations.AlterField(
            model_name='disponibilite',
            name='medecin',
            field=models.CharField(max_length=50),
        ),
    ]
