# Generated by Django 4.0.3 on 2024-01-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_disponibilite_idmed_alter_disponibilite_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilite',
            name='idMed',
        ),
    ]
