# Generated by Django 4.0.3 on 2024-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_remove_disponibilite_idmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilite',
            name='medecin',
            field=models.CharField(max_length=60),
        ),
    ]
