# Generated by Django 4.0.3 on 2024-01-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_alter_disponibilite_medecin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disponibilite',
            new_name='Horaires',
        ),
    ]
