# Generated by Django 4.0.3 on 2024-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_rename_disponibilite_horaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Horaires',
        ),
    ]
