# Generated by Django 4.0.3 on 2024-01-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
